### ISSUE TITLE
Inference code for MBARI Monterey Bay Benthic?

### ISSUE THREAD

**Issue by Jordan-Pierce** [fathomnet/models#2]
Hello, thanks for sharing these models.

Do you have there inference code available for the MBARI Monterey Bay Benthic (yolov5) model? Knowing the preprocessing methods would be very useful deploying the model.

Thanks,

Jordan

**Comment by lonnylundsten** [comment]
Hi Jordan,

For inference we use yolov5 with StrongSORT:
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet

Code to run that will look something like this:

`python track.py --yolo-weights '/PATH_TO/mbari-mb-benthic-33k.pt' --strong-sort-weights 'osnet_ain_x1_0_msmt17.pt' --save-txt --save-vid --agnostic-nms --conf-thres 0.7 --iou-thres 0.1 --device 0 --source /PATH_TO_YOUR_VIDEO/`

You may want to play around with confidence threshold and iou threshold. Also be sure to run inference on a video that is appropriate to this model,  i.e., continental shelf or slope of west coast USA.

-Lonny

**Comment by Jordan-Pierce** [comment]
Thanks!
